apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::801539518056:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AHHN4AOKKXZF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::801539518056:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T09:48:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1510"
  uid: 30e471a7-475d-4ca6-b819-da213cae4946
